### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by dinism** [KQMATH/moodle-mod_capquiz#105]
Hi. I'm PT-PT translator and these are not in AMOS. It's not possible translate IT:
- N-closest
- Chronological
- There is nothing to configure for this strategy

All in page "view_matchmaking_configuration.php"
In page of editing questions there is:
"The question ratings can be edited below. Changes are saved automatically."
Below or above? The sentence is below the questions.

All "available" English language strings for this plugin have been translated into Portuguese-Portugal in AMOS :)
Thanks

**Comment by sebastsg** [comment]
Thanks for your feedback. Added the missing language strings, and the location of that text. Should be out next version.
