### ISSUE TITLE
Wrong visualisation when rating is below current star level

### ISSUE THREAD

**Issue by hgeorgsch** [KQMATH/moodle-mod_capquiz#108]
When the student rating drops below the threshold for the last star obtained, the progress bar is drawn as if the student had a star less than he has.  It should be visualised as negative progress.
Styling for a negative progess bar was created previously, and it is strange that this does not currently work.

**Comment by sebastsg** [comment]
The negative bar only makes sense when no star has been achieved yet. Therefore, a new icon has been added. The star with only an outline indicates that the star is not achieved, and grey stars indicate lost stars.
