### ISSUE TITLE
Difficult for students to understand rating system 

### ISSUE THREAD

**Issue by hgeorgsch** [KQMATH/moodle-mod_capquiz#111]
It seems difficult for the students to understand the rating system, especially the difference between grey and yellow stars.
A couple of suggestions which may help include:
- A help button (question mark) to give an explanation.
- A mouse-over tip to explain the stars
- Showing the current and achieved rating, either in a mouse-over tip or alongside stars and bar
- A mouse-over tip to show the threshold for each star.
The mouse-over tips could be good «first issues».

**Comment by sebastsg** [comment]
#112 solves this
