### ISSUE TITLE
Strings 

### ISSUE THREAD

**Issue by dinism** [KQMATH/moodle-mod_capquiz#125]
I'm a PT-PT translator.
In page .../moodle/mod/capquiz/view_comments.php, some strings are hardcoded so it's not possible to translate them.
Thanks for the plugin
![imagem](https://user-images.githubusercontent.com/14828021/60031234-42207a00-969c-11e9-9693-c8ac8bb694e6.png)

**Comment by sebastsg** [comment]
Oops! Thanks for reporting this. Fixed in development branch, and will be part of next release.
