### ISSUE TITLE
Report interface, bad wording in UI

### ISSUE THREAD

**Issue by hgeorgsch** [KQMATH/moodle-mod_capquiz#153]
There is a checkbox: Show only answered attempts
It is really hard for the user to understand what that means.  Presumably, it implies that attempt rows are added to the DB when a question is posed, and completed if the student actually submits an answer, potentially leaving incomplete attempts in the DB.  A help text would ... help.

**Comment by sushantk-stud** [comment]
@hgeorgsch Could you please give me the line(s) of text that I should include. I am not exactly sure as what would be helpful to the user.

**Comment by andstor** [comment]
> Presumably, it implies that attempt rows are added to the DB when a question is posed, and completed if the student actually submits an answer, potentially leaving incomplete attempts in the DB.

Yes, that is correct 👍
