### ISSUE TITLE
Misleading message: grading completed

### ISSUE THREAD

**Issue by hgeorgsch** [KQMATH/moodle-mod_capquiz#169]
When grading is completed, CAPQuiz displays the message «Grading is completed.
You achieved 0 stars, which is a failing grade.» on every question.
This is annoying and may mislead the student into thinking that something is wrong. This should  be removed or rephrased. If displayed there should definitely be a reference to the deadline. Grading is complete only in the sense that the deadline for official grading is passed.

To devise the best solution here, we need some knowledge about how and when the message is created.

**Comment by andstor** [comment]
The message is generated here:
https://github.com/KQMATH/moodle-mod_capquiz/blob/9d30d7a3694868fd835eb31f5f521b9bb66e6cfa/templates/student_question_attempt.mustache#L33-L41

the language strings affected are these:
https://github.com/KQMATH/moodle-mod_capquiz/blob/b04a3987f16fd49f36d2fd68bfa38633173bf42f/lang/en/capquiz.php#L54-L55

**Comment by hgeorgsch** [comment]
Pull request to process.
