### ISSUE TITLE
Grunt errors in two AMD files.

### ISSUE THREAD

**Issue by hgeorgsch** [KQMATH/moodle-mod_capquiz#201]
/home/runner/work/moodle-mod_capquiz/moodle-mod_capquiz/moodle/mod/capquiz/amd/src/attempt.js
  52:27  error  Unexpected 'this'  no-invalid-this

/home/runner/work/moodle-mod_capquiz/moodle-mod_capquiz/moodle/mod/capquiz/amd/src/edit_questions.js
  159:25  warning  Do not nest ternary expressions  no-nested-ternary
  160:25  warning  Do not nest ternary expressions  no-nested-ternary
  171:15  error    Unexpected 'this'                no-invalid-this
  180:15  error    Unexpected 'this'                no-invalid-this
  190:25  error    Unexpected 'this'                no-invalid-this
  193:25  error    Unexpected 'this'                no-invalid-this
  194:25  error    Unexpected 'this'                no-invalid-this
  197:25  error    Unexpected 'this'                no-invalid-this
  217:34  error    Unexpected 'this'                no-invalid-this

**Comment by lucaboesch** [comment]
This seems fixed, @hgeorgsch.

**Comment by hgeorgsch** [comment]
Solved some time ago, probably by @lucaboesch
