### ISSUE TITLE
CAPQuiz questions page does not work (Moodle 4.0)

### ISSUE THREAD

**Issue by jorgfinsv** [KQMATH/moodle-mod_capquiz#208]
https://iirmoodle-dev.it.ntnu.no/mod/capquiz/edit.php?id=5&qpage=0

Tested with both safari and opera. Safari shows blank page while Opera shows HTTP ERROR 500

Suspected error location:
capquiz/edit.php

Discovered:
- At iirmoodle-dev.it.ntnu.no
- Making new course
- Adding CAPQuiz test
- At https://iirmoodle-dev.it.ntnu.no/mod/capquiz/view.php?id=5
- Clicks "Questions" button
- ERROR: HTTP ERROR 500

BUTTON WHICH TRIGGERS THE ERROR
<img width="1228" alt="Skjermbilde 2022-05-30 kl  12 23 49" src="https://user-images.githubusercontent.com/44703456/170973033-e3592218-6b1e-4b12-bd4b-f7b8104f64dc.png">

ERROR
<img width="653" alt="Skjermbilde 2022-05-30 kl  12 27 31" src="https://user-images.githubusercontent.com/44703456/170973344-1e30af18-29be-4c47-8393-fc0c938ee947.png">

**Comment by hgeorgsch** [comment]
See the developer doc's on question bank changes: https://docs.moodle.org/dev/Moodle_4.0_developer_update#Question_bank_changes

**Comment by BlackBlueGreens** [comment]
HTTPS 500 ERROR code is now solved, the page is now mostly left with 'deprecation' ERROR's.

**Comment by BlackBlueGreens** [comment]
The Page does load, but there are ERRORS left and some functionality has to be added, along side restructuring of the page

**Comment by BlackBlueGreens** [comment]
A new Error

× Debug info:
Error code: mixedtypesqlparam
× Stack trace:
line 923 of /lib/dml/moodle_database.php: dml_exception thrown
line 1005 of /lib/dml/pgsql_native_moodle_database.php: call to moodle_database->fix_sql_params()
line 1671 of /lib/dml/moodle_database.php: call to pgsql_native_moodle_database->get_records_sql()
line 42 of /question/editlib.php: call to moodle_database->get_record_sql()
line 316 of /question/editlib.php: call to get_module_from_cmid()
line 125 of /mod/capquiz/classes/output/question_bank_renderer.php: call to question_build_edit_resources()
line 72 of /mod/capquiz/classes/output/question_bank_renderer.php: call to mod_capquiz\output\question_bank_renderer->setup_question_edit()
line 86 of /mod/capquiz/classes/output/question_bank_renderer.php: call to mod_capquiz\output\question_bank_renderer->create_view()
line 238 of /mod/capquiz/classes/output/renderer.php: call to mod_capquiz\output\question_bank_renderer->render()
line 108 of /mod/capquiz/classes/output/renderer.php: call to class@anonymous/var/www/moodle/mod/capquiz/classes/output/renderer.php:214$79->render()
line 242 of /mod/capquiz/classes/output/renderer.php: call to mod_capquiz\output\renderer->display_tabbed_view()
line 45 of /mod/capquiz/edit.php: call to mod_capquiz\output\renderer->display_question_list_view()

PROBABLE CAUSE:
moodle-mod_capquiz --> classes --> output --> renderer.php
 line 33
PhpStorm suggests:
- undefined variable CFG

**Comment by BlackBlueGreens** [comment]
ANYONE else is welcome to assign themselves to this issue & try n solve it, ive moved to a different issue

**Comment by hgeorgsch** [comment]
Obvious errors have been fixed.  Testing is needed.  New bugs should be reported separately.
