### ISSUE TITLE
A CAPQuiz with a fixed number of questions asked

### ISSUE THREAD

**Issue by Bjoern-Ge** [KQMATH/moodle-mod_capquiz#216]
The idea of CAPQiuz is an endless quiz. 
In some use cases, it would be nice to have a fixed number of questions that are asked.

In this case, the teacher could select a fixed number of questions and the student gets a fixed result after answering those.

**Comment by hgeorgsch** [comment]
I appreciate the use case, but I think other quiz like activities handle it better than CAPQuiz could.
