### ISSUE TITLE
Images won't show in STACK questions used in a CAPquiz

### ISSUE THREAD

**Issue by 38315** [KQMATH/moodle-mod_capquiz#229]
**Describe the bug**
Images won't show in STACK questions used in a CAPquiz

I have tested multiple things: Including images in different ways (by file upload and by copy-pasting them into a STACK question), by using "change role to student" and by using real student view. I have tested that the same image *did* show correctly in the same STACK question in a normal Moodle Quiz (in student view as well as well as teacher view).

**To Reproduce**
1. Create or choose an existing STACK question that includes a png image.
2. Include it in a CAPquiz, and press "publish".
3. Change your role to student in order to preview the quiz. The image won't show. Instead a "broken image" will show, or the image wil just be left out.

**Expected behavior**

**Screenshots**
<img width="885" alt="Skjermbilde 2024-09-26 kl  10 41 38" src="https://github.com/user-attachments/assets/8acd2671-4625-4289-b47d-f4cb3c524b89">

<img width="759" alt="Skjermbilde 2024-09-26 kl  10 40 07" src="https://github.com/user-attachments/assets/089dfbe1-75b5-46b4-92ca-4d35cce1e688">

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser Safari 16.3

**Comment by hgeorgsch** [comment]
My guess is that this has to do with permissions.  It is conceivable that the image is uploaded to be available with the Quiz plugin, and then is not available with any other.  Personally, I have only used SVG incorporated in the HTML code, so I do not know how this works with separate image files.

Do you know more @sebastsg ?

**Comment by sebastsg** [comment]
#231 has the fix for this, awaiting merge until some more testing is done

@hgeorgsch I'm not sure if this has always been an issue with files in questions, or if it's due to recent-ish changes in Moodle. However, the issue got resolved after implementing `capquiz_question_pluginfile` in `lib.php`. It's somewhat based on the mod_quiz implementation.

**Comment by sebastsg** [comment]
Fixed in v0.8
