### ISSUE TITLE
Edit button and preview button not working in question list in CAPQuiz

### ISSUE THREAD

**Issue by 38315** [KQMATH/moodle-mod_capquiz#230]
**Describe the bug**
The "edit question" button and the "preview question" button do not work in the question list in CAPQuiz.

**To Reproduce**
1. Create a CAPQuiz question list.
2. Click on either the "edit question" button or the "preview question" button. An error message will show: "The requested URL was not found on this server".

**Screenshots**
<img width="517" alt="Skjermbilde 2024-09-26 kl  10 58 06" src="https://github.com/user-attachments/assets/76eb15ec-80b3-4f67-917e-742f9eeaf2ca">
<img width="526" alt="Skjermbilde 2024-09-26 kl  10 58 15" src="https://github.com/user-attachments/assets/71a6e5be-9e4e-4060-8190-b0f35bf2e477">
<img width="599" alt="Skjermbilde 2024-09-26 kl  10 59 10" src="https://github.com/user-attachments/assets/99f0a339-2df4-4b4a-aafc-a61d782fc099">

**Desktop (please complete the following information):**
 - OS: iOS 13.2.1
 - Browser: safari 16.3

**Comment by sebastsg** [comment]
#231 has the fix for this, awaiting merge until some more testing is done
