### ISSUE TITLE
Updating question rating is not intuitive

### ISSUE THREAD

**Issue by skrede** [KQMATH/moodle-mod_capquiz#26]

**Comment by skrede** [comment]
Need to press enter when modifying the value, this is not immediately obvious

**Comment by hgeorgsch** [comment]
This is not essential for in-house use, but critical for publication.

**Comment by sebastsg** [comment]
Added status indicator and autosaving.
Grey = nothing changed
Blue = updating
Green = saved successfully
Red = failed to save
