### ISSUE TITLE
Error baking badge image

### ISSUE THREAD

**Issue by skrede** [KQMATH/moodle-mod_capquiz#31]
Error baking badge image!

    line 1080 of /lib/badgeslib.php: call to debugging()
    line 448 of /lib/badgeslib.php: call to badges_bake()
    line 262 of /mod/capquiz/classes/capquiz_badge.php: call to badge->issue()
    line 90 of /mod/capquiz/classes/capquiz_question_engine.php: call to mod_capquiz\capquiz_badge->award()
    line 62 of /mod/capquiz/classes/capquiz_question_engine.php: call to mod_capquiz\capquiz_question_engine->maybe_award_badge()
    line 26 of /mod/capquiz/async.php: call to mod_capquiz\capquiz_question_engine->attempt_answered()
    line 40 of /mod/capquiz/async.php: call to mod_capquiz\question_attempt_async()
    line 45 of /mod/capquiz/async.php: call to mod_capquiz\capquiz_async()

**Comment by hgeorgsch** [comment]
This depends on #55

**Comment by hgeorgsch** [comment]
CAPQuiz should not be coupled with the badge system,
CAPQuiz now transfers a grade to the moodle gradebook. Badges should not, as far as we can see, be an integral part of CAPQuiz, but defined course level using standard Moodle features.
