### ISSUE TITLE
Error message when publishing CAPQuiz instance

### ISSUE THREAD

**Issue by skrede** [KQMATH/moodle-mod_capquiz#33]

**Comment by skrede** [comment]
This seems to stem from moodle internals

**Comment by hgeorgsch** [comment]
This seems to be a hidden error, which is only seen in moodle debug mode. If related problems occur, we will need to revisit it.

**Comment by sebastsg** [comment]
I have all debug info enabled, and attempted to get an error, but it all works fine. This is probably an outdated issue.
