### ISSUE TITLE
Edit questions from CAPQuiz editor?

### ISSUE THREAD

**Issue by hgeorgsch** [KQMATH/moodle-mod_capquiz#36]
Low priority.
It would be nice to be able to enter the question editor from the CAPquiz list editor.

**Comment by hgeorgsch** [comment]
This is also a problem in JazzQuiz.

**Comment by hgeorgsch** [comment]
It may be better to refer to the question bank. Unless we find a neat API which is designed for this kind of use in a plugin, we will be duplicating code, probably with strong coupling.

**Comment by skrede** [comment]
Agreed

**Comment by hgeorgsch** [comment]
This was incidentally resolved as part of another issue.
