### ISSUE TITLE
Import and merge lists

### ISSUE THREAD

**Issue by hgeorgsch** [KQMATH/moodle-mod_capquiz#37]
Low priority
It would be nice to be able to import several list (templates) into a new list.

**Comment by skrede** [comment]
Could show a list of question lists with checboxes to merge them into one. Have collapsible arrows for showing and hiding questions.

**Comment by sebastsg** [comment]
Started on this. Any requests for how UI should be?

**Comment by sebastsg** [comment]
Added to a new "Import" tab where a list of question lists are available, showing their questions if expanded.
