### ISSUE TITLE
Facilitate commenting on questions

### ISSUE THREAD

**Issue by skrede** [KQMATH/moodle-mod_capquiz#44]
Enable the controls by setting display option 'manualcomment' to VISIBLE in capquiz/classes/output/question_attempt_renderer.php

**Comment by hgeorgsch** [comment]
What we want from this is issue is to allow the students to give feedback on the question they are about to or just have answered. This is particularly important in the case of bugs, whether there are bugs in the plugin or in the solution.
This has proved important in MathGen, where we experienced some problems and it was very difficult to identify the question the student saw.

**Comment by sebastsg** [comment]
I think "manualcomment" is for instructors, as far as I could tell.
A new text field in capquiz_attempt "feedback" was added. Updated it in privacy provider, to export it as well.
If the student leaves a comment while answering a question, that comment will be visible upon reviewing it on the next page, and the student can edit the comment or delete it entirely.

**Comment by sebastsg** [comment]
Added the comments list to question list.
