### ISSUE TITLE
Implement controls for selected questions in question bank list

### ISSUE THREAD

**Issue by skrede** [KQMATH/moodle-mod_capquiz#45]
Actions for buttons under 'Delete' and 'Move to>>' under the section "With selected" is not implemented. These buttons can be found in Questions-tab while logged in as instructor.

**Comment by skrede** [comment]
Hide these for now. Hide the element via CSS shenanigans.

**Comment by hgeorgsch** [comment]
We need to fix this (also in JazzQuiz). The elements have not been hidden.
User interface-wise, it is a good solution if the buttons are removed, and replaced by a quick link to the question bank.
I have documented some of the problems here: http://confluence.uials.no:8090/display/KQMATH/Question+selection+view, but I am not sure about all the details.

**Comment by hgeorgsch** [comment]
Solution needs to be copied from JazzQuiz.

**Comment by sebastsg** [comment]
This was not as straight forward as in JazzQuiz, but it eventually became clear how to fix it.
Moodle has hardcoded edit.php into their forms, so view_question_list.php had to be renamed to edit.php.
When deleting questions, CAPQuiz threw exceptions when it did not find a question, but now it will show "question is missing" instead. (This is only for instructor's question list - student will maybe need some other logic)
I also made a method in capquiz_urls that will get the course module id from either "id" or "cmid" parameter. This will make it a bit easier when trying to get it. (The method in question_bank_renderer must still exist though)
