### ISSUE TITLE
Redirects doesn't work if the moodle directory isn't in the web server root

### ISSUE THREAD

**Issue by andstor** [KQMATH/moodle-mod_capquiz#50]
This is tested on an Apache2 server.
Error 404: The requested URL /mod/capquiz/action.php was not found on this server.

**Comment by hgeorgsch** [comment]
Are you aware that the root URL must be defined in the moodle config.php?  If not, that probably explains the error.

**Comment by andstor** [comment]
Yes i’m aware of that. I do not think it is a config problem as there are no redirect problems elswhere in Moodle. It is only local to CAPQuiz.

**Comment by hgeorgsch** [comment]
It seems to be triggered by this line in classes/capquiz_urls.php:
        $url = capquiz_urls::create_view_url(capquiz_urls::$url_action);
Is capquiz_urls:: referring to the class?
I suppose one has forgotten to prefix the server root, but I'll leave the correction to someone who actually knows what the class is supposed to do.

**Comment by hgeorgsch** [comment]
Andre has confirmed that this bug persists after updating capquiz,

**Comment by hgeorgsch** [comment]
A new test server has been set up on hasc-moodle4 for this purpose. I am not sure how to reproduce the error; I would appreciate it if you drop by and show me, André.

**Comment by hgeorgsch** [comment]
Bug reproduced at moodle4.schaathun.net
