### ISSUE TITLE
Make number of stars for a question list variable

### ISSUE THREAD

**Issue by skrede** [KQMATH/moodle-mod_capquiz#53]
Only the database and possibly the configuration form prevents this at this time.

The rating required for each level could be stored as JSON in the database, similar to what is done for matchmaking and rating system configuration.

This should not be a problem for the front end and most of the back end

**Comment by sebastsg** [comment]
I fix! Done. Stored as comma separated list in new column. Stored as char 255, so there is a limit to number of stars or how long the numbers are.
