### ISSUE TITLE
Consider storing highest level not with the user in the database

### ISSUE THREAD

**Issue by skrede** [KQMATH/moodle-mod_capquiz#54]
Both user rating and highest attained level (number of stars) is stored with the user in the database. 
This is data about the user tied to a specific question list. 

Both rating and number of stars is presumably obsolete if the instructor decides to change question list after it has been published and attempted by students.

This is presumably a rare case and this issue does not seem important.

**Comment by hgeorgsch** [comment]
The rating of a student is now related to a given user and given capquiz activity. If the teacher radically changes the quiz (question list) the student rating is no longer meaningful, but we have to assume that the teacher knows what he is doing. Only the teacher, in the concrete situation, can decide whether to keep student ratings as the best estimate available or create a new activity to start afresh.
