### ISSUE TITLE
Badge system disabled

### ISSUE THREAD

**Issue by skrede** [KQMATH/moodle-mod_capquiz#55]
Fix the badge system and use it in CAPQuiz. The classes capquiz_badge_registry and capquiz_badge are responsible for this.

There seems to be a bug within moodle when badge type (column 'type' in the badge database table) is set to 'BADGE_TYPE_COURSE'. A malformed SQL query is attempted. This is solved by changing it to 'BADGE_TYPE_SITE', but this makes badges site wide and not course specific. Unsure what this is caused by.

Additionally, the images used for badges does not show when badges are created.

**Comment by hgeorgsch** [comment]
I assume this implies that the badge system has been disabled (as opposed requesting it to be(come) disabled).

**Comment by skrede** [comment]
Yes, that's right

**Comment by hgeorgsch** [comment]
Stars have been implemented internally in capquiz, without any dependency on badges. Badges were proposed as a means to implement stars, and there is currently no other need for badges. Therefore badges will remain disabled until the CAP system in itself is fully functional.

**Comment by hgeorgsch** [comment]
CAPQuiz now transfers a grade to the moodle gradebook.  Badges should not, as far as we can see, be an integral part of CAPQuiz, but defined course level using standard Moodle features.
