### ISSUE TITLE
Fixate a dependency strategy

### ISSUE THREAD

**Issue by hgeorgsch** [KQMATH/moodle-mod_capquiz#79]
We need to determine minimum versions of PHP and other underlying libraries and document the requirements.

**Comment by hgeorgsch** [comment]
CAPQuiz was originally published for Moodle 3.5 (LTS) as minimum. It should remain compatible with 3.5 until end of life. Minimum versions of PHP and other stuff should be those of Moodle 3.5.  Details should be looked up and documented in the github wiki.
Next version should obviously also support Moodle 3.7.

**Comment by sebastsg** [comment]
Added some info to the 'home' page on the wiki. Does this seem enough?

**Comment by andstor** [comment]
I moved the info from the 'home' page on the wiki to a new [requirements page](https://github.com/KQMATH/moodle-mod_capquiz/wiki/Requirements).

**Comment by hgeorgsch** [comment]
This is OK for now.  Please remember to add any info if obscure PHP libraries or whatever are added.
