### ISSUE TITLE
Cannot create new question set

### ISSUE THREAD

**Issue by hgeorgsch** [KQMATH/moodle-mod_capquiz#82]
The following error occurs when creating a new (empty) question set. Tested on Moodle 3.5, PHP 7.0, and newly reinstalled CAPQuiz (latest master).

Exception - Return value of mod_capquiz\capquiz_rating_system_registry::register_rating_systems() must be an instance of mod_capquiz\void, none returned

More information about this error
Debug info:
Error code: generalexceptionmessage
Stack trace:

    line 95 of /mod/capquiz/classes/rating_system/capquiz_rating_system_registry.php: TypeError thrown
    line 40 of /mod/capquiz/classes/rating_system/capquiz_rating_system_registry.php: call to mod_capquiz\capquiz_rating_system_registry->register_rating_systems()
    line 46 of /mod/capquiz/classes/capquiz_rating_system_loader.php: call to mod_capquiz\capquiz_rating_system_registry->__construct()
    line 170 of /mod/capquiz/classes/capquiz.php: call to mod_capquiz\capquiz_rating_system_loader->__construct()
    line 275 of /mod/capquiz/classes/capquiz.php: call to mod_capquiz\capquiz->rating_system_loader()
    line 119 of /mod/capquiz/classes/capquiz.php: call to mod_capquiz\capquiz->validate_matchmaking_and_rating_systems()
    line 91 of /mod/capquiz/classes/capquiz_question_registry.php: call to mod_capquiz\capquiz->assign_question_list()
    line 81 of /mod/capquiz/classes/capquiz_question_registry.php: call to mod_capquiz\capquiz_question_registry->assign_to_capquiz()
    line 56 of /mod/capquiz/classes/output/question_list_creator_renderer.php: call to mod_capquiz\capquiz_question_registry->create_question_list()
    line 86 of /mod/capquiz/classes/output/renderer.php: call to mod_capquiz\output\question_list_creator_renderer->render()
    line 109 of /mod/capquiz/classes/output/renderer.php: call to mod_capquiz\output\renderer->display_view()
    line 45 of /mod/capquiz/view_create_question_list.php: call to mod_capquiz\output\renderer->display_question_list_create_view()

**Comment by hgeorgsch** [comment]
Ah.  The void type was introduced in PHP 7.1.

**Comment by sebastsg** [comment]
I've commented out all instances of ": void" in the code.
