### ISSUE TITLE
Sort question display

### ISSUE THREAD

**Issue by hgeorgsch** [KQMATH/moodle-mod_capquiz#83]
It is difficult to keep track of existing questions in a quiz/question set.
It would help if the questions were sorted in rating order. This should be simple to do.
It would be even better if the questions could be organised by category when reviewing a question set, but this is expected to be harder to resolve.

**Comment by hgeorgsch** [comment]
This is critical.  It is practically impossible to design a good activity without a better UI. The issue is part of a wider discussion about interaction desgin, but probably the easiest quick fix.

**Comment by sebastsg** [comment]
Added sorting for both name and rating column. The page loads without sorting at first, and you click on the columns to alternate between ascending and descending. Indicated by arrow icons.
