### ISSUE TITLE
invalid install.xml file

### ISSUE THREAD

**Issue by danmarsden** [KQMATH/moodle-mod_capquiz#87]
It appears you have been hand-editing your install.xml file and have created an invalid badly formatted file that will fail to work in some sites. Please correct this by using the built in Moodle xmldb editing tool by loading the file, making a change to a comment inside one of your tables and then use the xmldb editor to save the file. (you may have to adjust permissions on the file to allow xmldb editor to save it.) - then when making future changes to the file, please continue to use the xmldb editor.

**Comment by sebastsg** [comment]
Fixed
