### ISSUE TITLE
Consider adding travis ci support

### ISSUE THREAD

**Issue by danmarsden** [KQMATH/moodle-mod_capquiz#89]
Some of the tests run by the Moodle.org plugins db which is reporting a number of errors with your  plugin here:
https://moodle.org/plugins/pluginversion.php?id=18189
(not all those issues must be fixed for approval in the plugins db, but it does give a nice green flag in your plugin db entry when they all pass)

can be run via travis-ci on each commit in your github repo. Making your code comply with the moodle coding guidelines also makes it much easier for the review team to review your code.
More information on this is here:
https://moodle.org/mod/forum/discuss.php?d=323384

but the short version:
grab this file:
https://github.com/moodlerooms/moodle-plugin-ci/blob/master/.travis.dist.yml
rename it as .travis.yml and put in the root of your github directory.
Go to:
https://travis-ci.org/profile/KQMATH
Flick the switch for this repo.

then on every commit you make to github it will fire off a request to travis to run the tests in .travis.yml and will give you traffic lights beside each commit and generate a report.

something else you might want to change:
in .travis.yml the default file has lines like this:

env:
global:

MOODLE_BRANCH=MOODLE_32_STABLE
you might want to add other branches to that list (or remove unsupported branches) so you could change it to something like:

env:
global:

MOODLE_BRANCH=MOODLE_33_STABLE
MOODLE_BRANCH=MOODLE_34_STABLE
MOODLE_BRANCH=MOODLE_35_STABLE

**Comment by andstor** [comment]
### Travis CI support is now added.

Every commit now triggers a Travis build. Depending on which branch the commit is issued to (or base branch in a pull request), different builds get executed.

Any commit committed to **branch master** will trigger a ***complete*** build, checking against several Moodle versions, databases and PHP versions. This also includes pull requests to master.
**Any other branch** will trigger a ***lighter*** (and relative fast) build (around 10 min) only against the latest stable Moodle version (3.6).


### Complete build test matrix is made up of:
* **Moodle version**
  1. Moodle 3.5
  2. Moodle 3.6
  3. Moodle master (allowed to fail)
* **DB**
  1. MySQL
  2. PostgreSQL
* **PHP version**
  1. 7.0
  2. 7.1
  3. 7.1


### Current status:
<table>
  <th>Branch</th>
  <th>Status</th>
  <tr>
    <td>master</td>
    <td><a href="https://travis-ci.org/KQMATH/moodle-qtype_shortmath"><img src="https://travis-ci.org/KQMATH/moodle-mod_capquiz.svg?branch=master"></a></td>
  </tr>
  <tr>
    <td>develop</td>
    <td><a href="https://travis-ci.org/KQMATH/moodle-qtype_shortmath"><img src="https://travis-ci.org/KQMATH/moodle-mod_capquiz.svg?branch=development"></a></td>
  </tr>
</table>
