### ISSUE TITLE
Filtering of questions doesn't work if the moodle directory isn't in the web server root

### ISSUE THREAD

**Issue by andstor** [KQMATH/moodle-mod_capquiz#94]
**Describe the bug**
Filtering of questions doesn't work if the moodle directory isn't in the web server root.
Possibly related to issue #50.

**To Reproduce**
1. Moodle directory needs to not be located in the web server root.
2. Go to the "Question list" editing page in CAPQuiz.
3. Click on the 'Select a category' dropdown, or any of the checkboxes below. 
_Note_: Everything works as expected from the button `[Create a new question...]` and down.
4. See error Error 404: The requested URL /moodle/moodle/mod/capquiz/edit.php was not found on this server.

**Additional context**
This is tested on an Apache2 server.

**Comment by sebastsg** [comment]
Fixed
