### ISSUE TITLE
Moodle precheck failures

### ISSUE THREAD

**Issue by danmarsden** [KQMATH/moodle-mod_capquiz#98]
It would be good for you to review the code precheck report in the moodle.org plugins db - Grunt is also showing a possible issues with your JS not being built:
https://moodle.org/plugins/pluginversion.php?id=18786

**Comment by sebastsg** [comment]
This issue should probably have been closed a while ago. The report is viewed occasionally, and the grunt issue is fixed. (At the moment still an issue that should be fixed in the next release)
