### ISSUE TITLE
Coding error prevents translating English language strings

### ISSUE THREAD

**Issue by germanvaleroelizondo** [KQMATH/moodle-mod_capquiz#99]
**Describe the bug**
No English language strings are available in AMOS (https://lang.moodle.org) for translations of this plugin 

**To Reproduce**

1. Go to https://lang.moodle.org
2. Register as a user
3. Try to list the plugin's English language strings by 
https://lang.moodle.org/local/amos/view.php?v=3600&t=1549567851&l=es_mx&c=capquiz

4. See error as there are no English language strings

Read about the cause (and fix) of this error in Moodle DEV documentation

https://docs.moodle.org/dev/Plugin_contribution_checklist#Strings

**Expected behavior**
All English language strings should be recognized by AMOS and ready for translators to translate.

**Screenshots**

**Additional context**

You seem to have string concatenation, that is not allowed.

**Comment by andstor** [comment]
Thank you for reporting this!
I do believe that I have corrected the errors, making ATMOS able to detect the English language strings. Translation should therefore be possible with the next release of CAPQuiz.

**Comment by germanvaleroelizondo** [comment]
Your plugin currently shows "Translation stats not available. "
https://moodle.org/plugins/translations.php?plugin=mod_capquiz

**Comment by andstor** [comment]
CAPCuiz v0.1.5 is now released. Translation is now functioning!

**Comment by germanvaleroelizondo** [comment]
All English language strings for this plugin have been translated into Mexican Spanish in AMOS :)

**Comment by andstor** [comment]
Thank you! Much appreciated 😊
